source 'https://github.com/littlstar/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"
workspace 'Hello Littlstar'

target "Hello Littlstar" do
  use_frameworks!
  pod 'LittlstarPlayerSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig = xcconfig.gsub(/ -l"GVRSDK"/, '')
        xcconfig = xcconfig.gsub(/ -framework "GTMSessionFetcher"/, '')
        xcconfig = xcconfig.gsub(/ -framework "GVRKit"/, '')
        xcconfig = xcconfig.gsub(/ -framework "GoogleToolboxForMac"/, '')
        File.open(xcconfig_path, "w") { |file| file << xcconfig }
    end
  end
end